// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bot

import (
	"github.com/yanzay/tbot/v2"
)

// Injectors from wire.go:

func Wire(client *tbot.Client) *handler {
	botService := ProvideService()
	botHandler := ProvideHandler(client, botService)
	return botHandler
}
